### ISSUE TITLE
think of more tasks to offer during the session

### ISSUE THREAD

**Issue by tatarchm** [locoschool/autumn_24#40]

**Comment by tatarchm** [comment]
One that might be cool (though a bit advanced): request a PIN code and check if the user input is correct. Nothing new on the hardware side, only LEDs and the remote control. On the software side this requires variables. But if someone is done with simpler stuff and wants to go further, we could quickly explain them the basics of working with variables.

**Comment by tatarchm** [comment]
Create something like a street light - or any multi-state indicator light for that matter. For example, switch between R and G, blink at the end of each cycle to warn about the coming change.

**Comment by voshch** [comment]
> On the software side this requires variables.
Technically could be done with nested conditions (which I think some students might realistically go for).

**Comment by tatarchm** [comment]
Another idea: remote-controlled synthesizer. Play different notes on a buzzer when pressing different buttons.
